"""added incident medias model

Revision ID: 1d322e5b53af
Revises: ef8650cfb7d6
Create Date: 2026-08-12 19:01:13.952413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d322e5b53af"
down_revision: str | Sequence[str] | None = "ef8650cfb7d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_medias",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("image_urls", sa.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("audio_url", sa.String(), nullable=True),
        sa.Column(
            "types",
            sa.ARRAY(postgresql.ENUM("IMAGE", "AUDIO", name="media_types_incident")),
            nullable=False,
        ),
        sa.Column("uploaded_by_profile_id", sa.UUID(), nullable=True),
        sa.Column("meta_data", sa.ARRAY(sa.JSON()), nullable=False),
        sa.Column("profile_audit_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_audit_id"], ["profile_audits.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_medias_incident_id"),
        "incident_medias",
        ["incident_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    op.drop_index(op.f("ix_incident_medias_incident_id"), table_name="incident_medias")
    op.drop_table("incident_medias")
    # ### end Alembic commands ###
