"""added incident medias model

Revision ID: 7ae2187350f4
Revises: 1d322e5b53af
Create Date: 2026-08-12 19:04:55.658052

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ae2187350f4"
down_revision: str | Sequence[str] | None = "1d322e5b53af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        op.f("incident_medias_incident_id_fkey"), "incident_medias", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "incident_medias",
        "incidents",
        ["incident_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incident_medias", type_="foreignkey")
    op.create_foreign_key(
        op.f("incident_medias_incident_id_fkey"),
        "incident_medias",
        "incidents",
        ["incident_id"],
        ["id"],
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
