"""added incident medias model

Revision ID: fa6b552951c4
Revises: 291cf01f6829
Create Date: 2026-08-15 09:06:39.382400

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa6b552951c4"
down_revision: str | Sequence[str] | None = "291cf01f6829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "incident_medias",
        sa.Column(
            "type",
            sa.ARRAY(postgresql.ENUM("IMAGE", "AUDIO", name="media_types_incident")),
            nullable=False,
        ),
    )
    op.drop_column("incident_medias", "types")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident_medias",
        sa.Column(
            "types",
            postgresql.ARRAY(
                postgresql.ENUM("IMAGE", "AUDIO", name="media_types_incident")
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("incident_medias", "type")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
